export const TABLE_OVERVIEWS = [
  {
    id: 1,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 2,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 3,
    users: 5,
    status: 'active',
  },
  {
    id: 4,
    users: 5,
    status: 'activl',
  },
  {
    id: 5,
    users: 5,
    status: 'inactive',
  },
  {
    id: 6,
    users: 5,
    status: 'overtime',
  },
  {
    id: 7,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 8,
    users: 5,
    status: 'active',
  },
  {
    id: 9,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 10,
    users: 5,
    status: 'active',
  },
  {
    id: 11,
    users: 5,
    status: 'active',
  },
  {
    id: 12,
    users: 5,
    status: 'active',
  },
  {
    id: 13,
    users: 5,
    status: 'activl',
  },
  {
    id: 14,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 15,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 16,
    users: 5,
    status: 'inactive',
  },
  {
    id: 17,
    users: 5,
    status: 'inactive',
  },
  {
    id: 18,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 19,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 20,
    users: 5,
    status: 'unconfirmed',
  },
  {
    id: 21,
    users: 5,
    status: 'overtime',
  },
  {
    id: 22,
    users: 5,
    status: 'active',
  },
  {
    id: 23,
    users: 5,
    status: 'active',
  },
  {
    id: 24,
    users: 5,
    status: 'overtime',
  },
]

export const OVERVIEW_STATUS = [
  {
    id: 0,
    label: 'Unconfirmed',
    value: 'unconfirmed',
    color: 'grey.light',
  },
  {
    id: 1,
    label: 'Active (under set time)',
    value: 'active',
    color: 'green.light',
  },
  {
    id: 2,
    label: 'Activl (over set time)',
    value: 'activl',
    color: 'yellow.main',
  },
  {
    id: 3,
    label: 'Table Inactive',
    value: 'inactive',
    color: 'red.light',
  },
]

export const STAFF_SHIFTS = [
  {
    id: 0,
    avatar: 'human/person1.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 1,
    avatar: 'human/person2.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 2,
    avatar: 'human/person3.png',
    online: false,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 3,
    avatar: 'human/person4.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 4,
    avatar: 'human/person5.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 5,
    avatar: 'human/person6.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 6,
    avatar: 'human/person7.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: true,
  },
  {
    id: 7,
    avatar: 'human/person8.png',
    online: true,
    time: '2:32:22',
    name: 'Wade Warren',
    role: 'SMM manager',
    address: 'Cardiff Dough&Co',
    active: false,
  },
]

export const MESSAGES = [
  {
    id: 0,
    author: 'Cardiff Dough&Co',
    time: '54 mins ago',
    content: 'Having entered The Blue Cup Coffee Shop, you’ll  walk into a world of fragrant coffee, healthy snacks  and fabulous decor.',
    like: 235,
    dislike: 235,
  },
  {
    id: 1,
    author: 'Cardiff Dough&Co',
    time: '54 mins ago',
    content: 'Having entered The Blue Cup Coffee Shop, you’ll  walk',
    like: 235,
    dislike: 235,
  },
  {
    id: 2,
    author: 'Cardiff Dough&Co',
    time: '54 mins ago',
    content: 'Having entered The Blue Cup Coffee Shop, you’ll  walk into a world of fragrant coffee, healthy snacks  and fabulous decor.',
    like: 235,
    dislike: 235,
  },
  {
    id: 3,
    author: 'Cardiff Dough&Co',
    time: '54 mins ago',
    content: 'Having entered The Blue Cup Coffee Shop, you’ll  walk',
    like: 235,
    dislike: 235,
  },
]